use cc1;
CREATE TABLE ETUDIANT(CODEETUDIANT INT, NOMETUDIANT VARCHAR(20), DDNETUDIANT DATE);
CREATE TABLE MATIERE(CODEMAT INT, NOMMATIERE VARCHAR(20), COEFMATIERE FLOAT);
CREATE TABLE ENSEIGNANT(CODEENS INT, NOMENS VARCHAR(30), GRADEENS VARCHAR(20), CODEMAT INT);
CREATE TABLE NOTE(CODEET INT, CODEMAT INT, NOTE FLOAT);

ALTER TABLE ETUDIANT 
    ADD PRIMARY KEY(CODEETUDIANT);
ALTER TABLE MATIERE
    ADD PRIMARY KEY(CODEMAT);
ALTER TABLE ENSEIGNANT
    ADD PRIMARY KEY(CODEENS),
    ADD FOREIGN KEY(CODEMAT) REFERENCES MATIERE(CODEMAT);
ALTER TABLE NOTE 
    ADD PRIMARY KEY(CODEET,CODEMAT),
    ADD FOREIGN KEY(CODEET) REFERENCES ETUDIANT(CODEETUDIANT),
    ADD FOREIGN KEY(CODEMAT) REFERENCES MATIERE(CODEMAT);
    
ALTER TABLE MATIERE 
    MODIFY COEFMATIERE INT NOT NULL DEFAULT(1); 
    
ALTER TABLE NOTE 
    ADD COLUMN DATEEVALUATION DATE;
    
ALTER TABLE NOTE 
    ADD CONSTRAINT CHECK(DATEEVALUATION = current_date());

