CREATE DATABASE CC2;
USE CC2;
CREATE TABLE REGION( CODEREGION INT PRIMARY KEY, LIBELLE VARCHAR(50));


CREATE TABLE HOTEL(CODEH INT PRIMARY KEY, NOMH VARCHAR(50), ADRESSE VARCHAR(100), 
        VILLE VARCHAR(30), TELEPHONE BIGINT , NOMBREETOILE SMALLINT, NUMREGION INT, NOMBREDECHAMBRES int,
        NOMCONTACT VARCHAR(50),CONSTRAINT 
        FOREIGN KEY(NUMREGION) references REGION(CODEREGION),
        UNIQUE(NOMH,VILLE));
        
        
CREATE TABLE TYPESEJOUR(NUMTYPE INT PRIMARY KEY, 
LIBELLETYPE VARCHAR(20) CHECK(LIBELLETYPE IN("luxe","nomade","hospitalisé","affaire")),
PRIX_NUIT FLOAT NOT NULL);


CREATE TABLE CLIENT(CODEC INT PRIMARY KEY auto_increment, nom varchar(30), PRENOM VARCHAR(30), GSM INT,
		MAIL VARCHAR(30), ADRESS VARCHAR(60), PAYS VARCHAR(30));
        
        
CREATE TABLE RESERVATION(CODERES INT PRIMARY KEY AUTO_INCREMENT, NUMCLIENT INT, NUMTYPE INT, CODEH INT,
DATEDEBUT DATE ,DATEFIN DATE, MONTANT FLOAT,
CONSTRAINT foreign key(NUMCLIENT) REFERENCES CLIENT(CODEC),
FOREIGN KEY(NUMTYPE) REFERENCES TYPESEJOUR(NUMTYPE),
FOREIGN KEY(CODEH) REFERENCES HOTEL(CODEH),CHECK(DATEDEBUT < DATEFIN));

ALTER TABLE CLIENT
MODIFY ADRESS VARCHAR(300)