USE CC2;
SELECT H.* FROM HOTEL H INNER JOIN REGION R ON H.NUMREGION = R.CODEREGION ORDER BY R.LIBELLE;
SELECT TS.PRIX_NUIT FROM RESERVATION R INNER JOIN
TYPESEJOUR TS ON R.NUMTYPE = TS.NUMTYPE; 
SELECT TS.PRIX_NUIT FROM RESERVATION R INNER JOIN
TYPESEJOUR TS ON R.NUMTYPE = TS.NUMTYPE where r.CODERES =3;
UPDATE RESERVATION SET MONTANT = DATEDIFF(DATEFIN,DATEDEBUT)*(SELECT PRIX_NUIT FROM (SELECT TS.PRIX_NUIT FROM RESERVATION R INNER JOIN 
TYPESEJOUR TS ON R.NUMTYPE = TS.NUMTYPE where R.CODERES =3) AS PO) WHERE CODERES = 3;

UPDATE RESERVATION SET MONTANT = DATEDIFF(DATEFIN,DATEDEBUT)*(SELECT PRIX_NUIT FROM (SELECT TS.PRIX_NUIT FROM RESERVATION R INNER JOIN 
TYPESEJOUR TS ON R.NUMTYPE = TS.NUMTYPE where R.CODERES =4) AS PQ) WHERE CODERES = 4;

SELECT TS.*, COUNT(R.NUMTYPE) AS NT FROM TYPESEJOUR TS INNER JOIN RESERVATION R ON TS.NUMTYPE = R.NUMTYPE 
GROUP BY R.NUMTYPE ORDER BY R.NUMTYPE; 

SELECT VILLE, COUNT(NOMBREETOILE) AS NUMB FROM HOTEL WHERE NOMBREETOILE =5 GROUP BY VILLE ORDER BY NUMB DESC LIMIT 1;

SELECT R.LIBELLE, count(NOMH)AS NUMBHOT FROM REGION R INNER JOIN HOTEL H ON R.CODEREGION = H.NUMREGION
GROUP BY R.LIBELLE ORDER BY NUMBHOT DESC;

SELECT H.* FROM HOTEL H INNER JOIN RESERVATION R ON H.CODEH = R.CODEH ;

ALTER TABLE CLIENT
ADD COLUMN COMMENTAIRE VARCHAR(100);

UPDATE CLIENT SET COMMENTAIRE = "marocain" WHERE PAYS = "maroc";
UPDATE CLIENT  SET COMMENTAIRE =  "de l'étranger" WHERE PAYS != "maroc";

ALTER TABLE CLIENT 
DROP COLUMN PAYS;

DROP TABLE RESERVATION;
DROP TABLE HOTEL;
DROP TABLE REGION;
DROP TABLE TYPESEJOUR;
DROP TABLE CLIENT;