DROP DATABASE exam;
CREATE DATABASE exam;
USE exam;
CREATE TABLE CLIENT(CODECL INT, NOMCL VARCHAR(50), PRENOMCL VARCHAR(50),
 ADRESSE VARCHAR(255), CODEPOSTALE BIGINT, VILLE VARCHAR(50));
 CREATE TABLE PRODUIT(REFERENCEPRODUIT INT, DESIGNATION VARCHAR(100), PRIX FLOAT);
 CREATE TABLE TECHNICIENS(CODETECHNICIEN INT, NOMTECHNICIEN VARCHAR(50), PRENOMTECHNICIEN VARCHAR(100),
 TAUXHORAIRE INT);
CREATE TABLE INTERVENTION(NUMEROINTERVENTION INT, DATE DATE ,RAISON VARCHAR(255), CODECLIENT INT,
REFPRODUIT INT, CODETECHNICIEN INT);
 
 ALTER TABLE CLIENT
 ADD PRIMARY KEY(CODECL);
 
ALTER TABLE  PRODUIT 
ADD PRIMARY KEY(REFERENCEPRODUIT);

ALTER TABLE  TECHNICIENS
ADD PRIMARY KEY(CODETECHNICIEN);

ALTER TABLE  INTERVENTION
ADD PRIMARY KEY(NUMEROINTERVENTION);

ALTER TABLE INTERVENTION 
ADD FOREIGN KEY(CODECLIENT) REFERENCES CLIENT(CODECL),
ADD FOREIGN KEY(REFPRODUIT) REFERENCES PRODUIT(REFERENCEPRODUIT) ,
ADD FOREIGN KEY(CODETECHNICIEN) REFERENCES TECHNICIENS(CODETECHNICIEN);

ALTER TABLE TECHNICIENS
ADD CONSTRAINT CHECK(TAUXHORAIRE >= 100);


ALTER TABLE CLIENT
RENAME COLUMN NOMCL TO NOMCLIENT,
RENAME COLUMN PRENOMCL TO PRENOMCLIENT;

ALTER TABLE PRODUIT 
MODIFY DESIGNATION VARCHAR(100) NOT NULL;

ALTER TABLE TECHNICIENS
MODIFY TAUXHORAIRE INT CHECK(TAUXHORAIRE >= 100) DEFAULT(100);
ALTER TABLE INTERVENTION 
ADD CONSTRAINT CHECK(DATE = sysdate()); 