USE EGI;

SELECT NOM, POSTE FROM EMP WHERE POSTE = (SELECT POSTE FROM EMP WHERE NOM = 'Madhoun');


SELECT NOM, SALAIRE, NUMDEP FROM EMP WHERE SALAIRE > any(SELECT SALAIRE
FROM EMP WHERE NUMDEP = 31 ) ORDER BY NUMDEP,SALAIRE;


SELECT NOM, SALAIRE, NUMDEP FROM EMP WHERE SALAIRE > (SELECT MAX(SALAIRE) 
FROM EMP WHERE NUMDEP = 31 ) ORDER BY NUMDEP,SALAIRE;

SELECT NOM,POSTE FROM EMP WHERE NUMDEP = 31 AND POSTE IN (SELECT POSTE FROM EMP WHERE NUMDEP =32);

SELECT NOM,POSTE FROM EMP WHERE  NUMDEP = 31 AND POSTE NOT IN (SELECT POSTE FROM EMP WHERE NUMDEP =32);

SELECT NOM, POSTE, SALAIRE FROM EMP WHERE POSTE =(SELECT POSTE FROM EMP WHERE NOM = 'Alaoui' ) 
AND SALAIRE = (SELECT SALAIRE FROM EMP WHERE NOM = 'Alaoui');

SELECT E.NUMDEP , E.NOM, E.salaire FROM EMP E INNER JOIN 
(SELECT NUMDEP, avg(SALAIRE) AS O FROM EMP GROUP BY NUMDEP) H ON E.NUMDEP = H.NUMDEP
WHERE E.SALAIRE > H.O ORDER BY NUMDEP;

SELECT NUME, NOM, PRENOM FROM EMP 
WHERE NUMDEP IN (SELECT NUMDEP FROM EMP WHERE POSTE = 'representent');



select numdep,nom from dept
where numdep not in (select numdep from emp);


SELECT * FROM DEpt;