SELECT * FROM PATIENTS WHERE CHAR_length(NOMPATIENT) <= 6;
SELECT SUBSTRING(NOMPATIENT,1,4) AS FFCHARS FROM PATIENTS;
SELECT date_format(C.DATECONSULTATION,"%d %b %y") AS DATE_CONSULTATION 
FROM PATIENTS P INNER JOIN SUIVIS S ON P.CODEPATIENT = S.CODEPATIENT INNER JOIN CONSULTATION C
ON S.NUMCONSULTATION = C.NUMCONSULTATION WHERE P.CODEPATIENT = 1;
SELECT DATEDIFF(CURDATE(),DDN) AS AGEENJR FROM PATIENTS;
SELECT DAY(DDN) AS JRN FROM PATIENTS;
SELECT AVG(POIDS) PMOY FROM PATIENTS;
SELECT DDN FROM PATIENTS ORDER BY DDN DESC LIMIT 1;
SELECT M.DESIGNATION, COUNT(P.CODEPATIENT) AS NUMBERS FROM PATIENTS P INNER JOIN SOUFRIR S ON P.CODEPATIENT=S.CODEPATIENT
INNER JOIN MALADIES M ON S.CODEMALADIE = M.CODEMALADIE WHERE M.DESIGNATION = "Hypertension" GROUP BY DESIGNATION;
SELECT YEAR(C.DATECONSULTATION) AS YC , count(P.CODEPATIENT) AS NUMBERS FROM CONSULTATION C INNER JOIN SUIVIS S 
ON C.NUMCONSULTATION = S.NUMCONSULTATION INNER JOIN PATIENTS P ON S.CODEPATIENT = P.CODEPATIENT 
WHERE YEAR(C.DATECONSULTATION) = 2023 GROUP BY YEAR(DATECONSULTATION);
SELECT GRPSANGUIN, AVG(POIDS) AS PMOY FROM PATIENTS GROUP BY GRPSANGUIN;
SELECT P.NOMPATIENT,P.PRENOMPATIENT, MIN(DATECONSULTATION) AS MDC FROM PATIENTS P INNER JOIN SUIVIS S ON P.CODEPATIENT = S.CODEPATIENT 
INNER JOIN CONSULTATION C ON S.NUMCONSULTATION = C.NUMCONSULTATION GROUP BY P.NOMPATIENT, PRENOMPATIENT;
SELECT TYPECONSULTATION, COUNT(TYPECONSULTATION) FROM CONSULTATION GROUP BY TYPECONSULTATION;
SELECT * FROM PATIENTS;